#-----------------------------------------------------------------------
#
#   applicaton-common : Default Common Configuation
#   kubernetes PV(Persistent Volume) : /DATA  
#    
#-----------------------------------------------------------------------

spring:
  config:
    activate:
      on-profile: local

props:
  common:
    baseFilePath: /XXX/XXXX/DATA/
    advehicleSwPath: files/advehicle_sw
  
---
 
spring:
  config:
    activate:
      on-profile: dev

props:
  common:
    baseFilePath: /DATA/
    advehicleSwPath: files/advehicle_sw
 
---
 
spring:
  config:
    activate:
      on-profile: prod

props:
  common:
    baseFilePath: /DATA/
    advehicleSwPath: files/advehicle_sw
